name: e2e test ascenda UI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
        matrix:
          node-version: [20.x]

    steps:
      - uses: actions/checkout@v4
      - name: Check repository contents
        run: ls -R $GITHUB_WORKSPACE

      - name: Set up Python 3.12.1
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.1'

      - name: Update pip to latest ver
        run: pip install -U pip

      - name: Install rf dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools
          python -m pip install --upgrade robotframework
          python -m pip install --upgrade robotframework-requests
          python -m pip install --upgrade robotframework-faker
          python -m pip install --upgrade robotframework-jsonlibrary
          python -m pip install --upgrade robotframework-browser

      - name: Install node dependencies
        run: python -m Browser.entry init

      - name: Run robot tests for ui
        run: robot --nostatusrc tests/ui
